spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate.ddl-auto: validate
  liquibase:
    change-log: classpath:db-changelog.xml
spring.sql.init.platform: postgres

smlr:
  prefix: http://localhost:8080/
